---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: check ci env network
  image: ubuntu:latest
  commands:
  - apt update -y -qq
  - apt install -y curl whois jq
  - curl ipinfo.io
  - whois $(curl ipinfo.io | jq .ip | tr -d '"')

- name: check machine spec
  image: ubuntu:latest
  commands:
  - cat /proc/cpuinfo
  - free -m
  - cat /proc/meminfo
