sudo: required
language: ruby

before_install:
  - sudo apt-get install whois curl jq

script:
  - whois $(curl ipinfo.io | jq .ip | tr -d '"')
  - cat /proc/cpuinfo
  - free -m
  - cat /proc/meminfo
