image: ubuntu

install:
- apt update -y -qq
- apt install curl whois jq

check_network:
- curl ipinfo.io
- whois $(curl ipinfo.io | jq .ip | tr -d '"')

check_machine:
- sh: cat /proc/cpuinfo
- sh: free -m
- sh: cat /proc/meminfo

build: off
