name: CI

on: [push]

jobs:
  check_network:
    runs-on: ubuntu-latest
    steps:
    - curl ipinfo.io
    - whois $(curl ipinfo.io | jq .ip | tr -d '"')

  check_machine:
    runs-on: ubuntu-latest
    steps:
    - cat /proc/cpuinfo
    - free -m
    - cat /proc/meminfo
